require "./accounts"
require "./announcements"
require "./apps"
require "./blocks"
require "./conversations"
require "./custom_emojis"
require "./directory"
require "./domain_blocks"
require "./favourites"
require "./follow_requests"
require "./follows"
require "./instances"
require "./lists"
require "./markers"
require "./media"
require "./mutes"
require "./notifications"
require "./oembed"
require "./polls"
require "./reports"
require "./scheduled_statuses"
require "./search"
require "./statuses"
require "./timelines"
require "./trends"

module Mastodon
  module REST
    module Api
      include Mastodon::REST::Accounts
      include Mastodon::REST::Announcements
      include Mastodon::REST::Apps
      include Mastodon::REST::Blocks
      include Mastodon::REST::Conversations
      include Mastodon::REST::CustomEmojis
      include Mastodon::REST::Directory
      include Mastodon::REST::DomainBlocks
      include Mastodon::REST::Favourites
      include Mastodon::REST::FollowRequests
      include Mastodon::REST::Follows
      include Mastodon::REST::Instances
      include Mastodon::REST::Lists
      include Mastodon::REST::Markers
      include Mastodon::REST::Media
      include Mastodon::REST::Mutes
      include Mastodon::REST::Notifications
      include Mastodon::REST::OEmbed
      include Mastodon::REST::Polls
      include Mastodon::REST::Reports
      include Mastodon::REST::ScheduledStatuses
      include Mastodon::REST::Search
      include Mastodon::REST::Statuses
      include Mastodon::REST::Timelines
      include Mastodon::REST::Trends
    end
  end
end
